//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailType
    {
        public EmailType()
        {
            this.Email = new HashSet<Email>();
        }
    
        public System.Guid EmailType_Id { get; set; }
        public string EmailType_Name { get; set; }
    
        public virtual ICollection<Email> Email { get; set; }
    }
}
