//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Email = new HashSet<Email>();
            this.Phone = new HashSet<Phone>();
            this.EmpTask = new HashSet<EmpTask>();
        }
    
        public System.Guid Employee_Id { get; set; }
        public string Employee_FIO { get; set; }
    
        public virtual ICollection<Email> Email { get; set; }
        public virtual ICollection<Phone> Phone { get; set; }
        public virtual ICollection<EmpTask> EmpTask { get; set; }
    }
}
