//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpTask
    {
        public EmpTask()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public System.Guid Task_Id { get; set; }
        public string Task_Name { get; set; }
        public string Task_DeadLine { get; set; }
        public bool Task_PrevCompleted { get; set; }
        public bool Task_Completed { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
