//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public System.Guid Phone_Id { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.Guid> Employee_Id { get; set; }
        public Nullable<System.Guid> PhoneType_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PhoneType PhoneType { get; set; }
    }
}
