//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneType
    {
        public PhoneType()
        {
            this.Phone = new HashSet<Phone>();
        }
    
        public System.Guid PhoneType_Id { get; set; }
        public string PhoneType_Name { get; set; }
    
        public virtual ICollection<Phone> Phone { get; set; }
    }
}
